name: drupal-starter-pack

services:
  db:
    image: mariadb:11
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  drupal:
    build: .
    user: www-data:www-data
    volumes:
      - ./theme:/opt/drupal/web/themes/custom/theme
    ports:
      - 88:80
    restart: always
    environment:
      DB_NAME: drupal
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: ${COMPOSE_PROJECT_NAME}-db-1
      SALT: ${DRUPAL-SALT}

volumes:
  db: